export const ACTION_TYPES = {
  INCREMENT_GLOBAL: "INCREMENT_GLOBAL",
  DECREMENT_GLOBAL: "DECREMENT_GLOBAL",
  INCREMENT_LOCAL: "INCREMENT_LOCAL",
  DECREMENT_LOCAL: "DECREMENT_LOCAL",
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
};
